### ISSUE TITLE
Syntax error in IE11

### ISSUE THREAD

**Issue by yoann-chambrun** [urbit/argon2-wasm#10]
Hi, 

we use this library and we have an issue when we called this method : argon2.hash

Please find our code to test : 

```import argon2 from "argon2-wasm";

// Return the password hash if possible, otherwise the clear password
/**
  @param {string} username
  @param {string} password
  @param {string|null} token
  @return {Promise}
 */
export async function hash(password) {
  try {
    /* eslint-disable camelcase */
    const { hash_len, m, p, salt, t } = {hash_len: 16, m: 512, p: 2, salt: "random", t:2};

    const { encoded } = await argon2.hash({
      pass: password,
      salt: Uint8Array.from(atob(salt), c => c.charCodeAt(0)),
      time: t,
      mem: m,
      hashLen: hash_len,
      parallelism: p,
      type: argon2.types.Argon2i,
      distPath: "dist",
    });
    return encoded;
  } catch (error) {
    return password;
  }
}
```

Thanks

**Comment by Fang-** [comment]
> Argon2i

If you don't care about the Urbit-specific Argon2u, it's probably better to use the repository we based this off of: [antelle/argon2-browser](https://github.com/antelle/argon2-browser)

(Also, when filing an issue, a better description of your error will let people help you better. Mention what/where exactly the syntax error is, etc etc.)
