### ISSUE TITLE
Need new/latest version on NPM

### ISSUE THREAD

**Issue by Fang-** [urbit/argon2-wasm#4]
This latest commit https://github.com/urbit/argon2-wasm/commit/e1df50415ba651125508a9368766c467c22884eb needs to be pushed on to NPM. Not sure who has the creds/skills to do this.

cc @jtobin @joemfb @c-johnson ?

**Comment by joemfb** [comment]
I have my own credentials, and have published my own stuff. Not sure if we have a process for these things yet.
